// 学習する単語リスト（プロトタイプ: 30語）
// レベルを増やせばそのまま1000語まで拡張できる構造にしてあります。
const WORDS = [
  { en: "apple", ja: "りんご" },
  { en: "banana", ja: "バナナ" },
  { en: "orange", ja: "オレンジ" },
  { en: "cat", ja: "ねこ" },
  { en: "dog", ja: "いぬ" },
  { en: "bird", ja: "とり" },
  { en: "fish", ja: "さかな" },
  { en: "lion", ja: "ライオン" },
  { en: "elephant", ja: "ぞう" },
  { en: "rabbit", ja: "うさぎ" },
  { en: "book", ja: "ほん" },
  { en: "pen", ja: "ペン" },
  { en: "pencil", ja: "えんぴつ" },
  { en: "chair", ja: "いす" },
  { en: "desk", ja: "つくえ" },
  { en: "school", ja: "がっこう" },
  { en: "friend", ja: "ともだち" },
  { en: "family", ja: "かぞく" },
  { en: "mother", ja: "おかあさん" },
  { en: "father", ja: "おとうさん" },
  { en: "sister", ja: "しまい（あね・いもうと）" },
  { en: "brother", ja: "きょうだい（あに・おとうと）" },
  { en: "water", ja: "みず" },
  { en: "milk", ja: "ぎゅうにゅう" },
  { en: "bread", ja: "パン" },
  { en: "rice", ja: "ごはん" },
  { en: "red", ja: "あか" },
  { en: "blue", ja: "あお" },
  { en: "yellow", ja: "きいろ" },
  { en: "green", ja: "みどり" },
];
